name: pyCompress4_numcodecs
channels:
  - conda-forge
dependencies:
  - click
  - codecov
  - dask
  - dask-jobqueue
  - nbsphinx
  - netcdf4
  - numpydoc
  - pip
  - pytest
  - pytest-cov
  - python=3.7
  - scipy
  - xarray
  - zarr
  - zfpy
  - pip:
       - git+https://github.com/zarr-developers/numcodecs.git
